apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: MYAPP
  labels:
    app: MYAPP
spec:
  replicas: 3
  selector:
    matchLabels:
      app: MYAPP
  template:
    metadata:
      labels:
        app: MYAPP
    spec:
      containers:
      - name: MYAPP
        image: nginx
        command:
          - sleep
          - "3600"
        ports:
        - name: web
          containerPort:  80
          protocol: TCP